### ISSUE TITLE
Sliding an item left or right (but not deleting it), then scrolling up / down fast causes the program to crash

### ISSUE THREAD

**Issue by elsonsolano** [Azoft/CarouselLayoutManager#29]
Hello.

I used your library in order to stack cards for my program. 
Since it is a RecyclerView, I have added an ItemTouchListener to the RecyclerView in order to slide the items.

All is fine. But one issue I encountered was that when I slide the item left or right (but not removing it), then scrolling the list up / down very fast, my program would crash and will say

java.lang.IllegalArgumentException: Tmp detached view should be removed from RecyclerView before it can be recycled: ViewHolder{f0f213a position=5 id=-1, oldPos=-1, pLpos:-1 tmpDetached no parent}
                                                                          at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5424)
                                                                          at android.support.v7.widget.RecyclerView.removeAnimatingView(RecyclerView.java:1242)
                                                                          at android.support.v7.widget.RecyclerView$ItemAnimatorRestoreListener.onAnimationFinished(RecyclerView.java:11151)
                                                                          at android.support.v7.widget.RecyclerView$ItemAnimator.dispatchAnimationFinished(RecyclerView.java:11651)
                                                                          at android.support.v7.widget.SimpleItemAnimator.dispatchMoveFinished(SimpleItemAnimator.java:279)
                                                                          at android.support.v7.widget.DefaultItemAnimator$6.onAnimationEnd(DefaultItemAnimator.java:304)
                                                                          at android.support.v4.view.ViewPropertyAnimatorCompatJB$1.onAnimationEnd(ViewPropertyAnimatorCompatJB.java:47)
                                                                          at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1114)
                                                                          at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
                                                                          at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
                                                                          at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:628)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:158)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Hoping for your response on this issue. Thank you.

**Comment by mig35** [comment]
Hi @elsonsolano.
As I can see this is connected with RecyclerView and not it's layout manager. Why do you think this issue is connected with CarouselLayoutManager?
