### ISSUE TITLE
itemCount==0 的时候发生NullPointerException, 希望可以解决一下, 谢谢Thanks

### ISSUE THREAD

**Issue by Lerist** [Azoft/CarouselLayoutManager#3]
Log:
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                        at com.azoft.carousellayoutmanager.CarouselLayoutManager.getScrollItemSize(CarouselLayoutManager.java:574)
                                                                        at com.azoft.carousellayoutmanager.CarouselLayoutManager.getMaxScrollOffset(CarouselLayoutManager.java:415)
                                                                        at com.azoft.carousellayoutmanager.CarouselLayoutManager.getCurrentScrollPosition(CarouselLayoutManager.java:404)
                                                                        at com.azoft.carousellayoutmanager.CarouselLayoutManager.getOffsetCenterView(CarouselLayoutManager.java:584)
                                                                        at com.azoft.carousellayoutmanager.CenterScrollListener.onScrollStateChanged(CenterScrollListener.java:25)
                                                                        at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:3990)

**Comment by mig35** [comment]
Hi, Lerist!

We confirm this issue and will update our library asap. Thanks!

**Comment by mig35** [comment]
fixed in: compile 'com.azoft.carousellayoutmanager:carousel:1.0.2'
