### ISSUE TITLE
bug with width of layout element

### ISSUE THREAD

**Issue by flooduk** [Azoft/CarouselLayoutManager#33]
Hi! 

i used this library v1.1.9, and catch crash on rooted device nexus 5x with cyanogenmod and android 7.1.1. 
bug is unboxing Integer mDecoratedChildWidth to int, when mDecoratedChildWidth == null
i looked v1.2.0, and this version is not fix this crash

info from fabric.io:

Device Nexus 5 CAF
ORIENTATION Portrait
PROXIMITY On

OS VERSION 7.1.1
UI ORIENTATION Portrait
ROOTED Yes

crash log:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.azoft.carousellayoutmanager.CarouselLayoutManager.getScrollItemSize(Unknown Source:590)
       at com.azoft.carousellayoutmanager.CarouselLayoutManager.scrollBy(Unknown Source:258)
       at com.azoft.carousellayoutmanager.CarouselLayoutManager.scrollHorizontallyBy(Unknown Source:233)
       at android.support.v7.widget.RecyclerView.scrollByInternal(Unknown Source:1636)
       at android.support.v7.widget.RecyclerView.onTouchEvent(Unknown Source:2759)
       at android.view.View.dispatchTouchEvent(View.java:10024)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(Unknown Source:67)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
       at android.view.View.dispatchPointerEvent(View.java:10244)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6252)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6226)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6187)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6355)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6326)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6378)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:615)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6126)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by mig35** [comment]
Hi @flooduk.
Thanks for your issue. Please check 1.2.1 version.
But it is strange to see this issue...
